name: 'Build Package'
description: 'Package Building Action'
inputs:
  package_type:
    description: 'Type of package to build, currently deb or RPM'
    required: true
    default: 'dpkg'
outputs:
  result:
    description: "Build result"
    value: ${{ steps.gen_output.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Build ${{ inputs.package_type }} package
      shell: bash
      run: |
          ls -lah
          mkdir build && cd build
          cmake ..
          cmake --build . --target ${{ inputs.package_type }} --parallel $(nproc)

    - name: Save packages
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.package_type }}_packages
        path: packages