name: Build RPM Package
on:
  push:
    branches:
      - main

jobs:
  rpm_package_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build rpm packages
        run: |
          ls -lah
          mkdir build && cd build
          cmake ..
          cmake --build . --target rpm --parallel $(nproc)
      - name: Save packages
        uses: actions/upload-artifact@v2
        with:
          name: RPM Packages
          path: packages
